apps/core/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import *


app_name = 'core'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='core:welcome', permanent=False)),
    path('welcome/', welcome, name='welcome'),
    path('about/', about, name='about'),

    path('products/', products, name='products'),
    path('products/<int:pk>/', ProductsDetails.as_view(), name='product-details'),
    path('products/<int:pk>/edit/', ProductUpdateView.as_view(), name='product-edit'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product-delete'),

    path('brands/', brands, name='brands'),
    path('brands/<int:pk>/delete/', BrandDeleteView.as_view(), name='brand-delete'),

    path('categories/', categories, name='categories'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete')
]

apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('sign-up/', views.SignUpView.as_view(), name='sign-up'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('list/', views.UserListView.as_view(), name='user-list'),
    path('list/<int:pk>', views.ChangeUserGroupView.as_view(), name='change-group'),

    path('profile/', RedirectView.as_view(pattern_name='core:products', permanent=False))
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('accounts/', include('apps.users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models/brand.py
from django.db import models


class Brand(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name

apps/core/models/catalog.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=160)

    def __str__(self):
        return self.name

apps/core/models/product.py
from django.db import models

from apps.core.models.brand import Brand
from apps.core.models.catalog import Category


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    price = models.FloatField()
    amount = models.IntegerField(default=1)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.name}: {self.price}UAH, x{self.amount}"

apps/core/forms.py
from django import forms

from apps.core.models import Product, Brand, Category


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'required': True
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'required': True
            }),
            'price': forms.NumberInput(attrs={
                'class': 'form-control',
                'required': True,
                'step': 0.5,
                'min': 0
            }),
            'amount': forms.NumberInput(attrs={
                'class': 'form-control',
                'required': True,
                'min': 0
            }),
            'image': forms.FileInput(attrs={
                'class': 'form-control',
                'required': True
            }),
            'brand': forms.Select(attrs={
                'class': 'form-control',
                'required': False
            }),
            'category': forms.Select(attrs={
                'class': 'form-control',
                'required': False
            })
        }


class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = '__all__'

        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'required': True
            })
        }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'required': True
            })
        }

apps/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.generic import UpdateView, DetailView, DeleteView

from apps.core.forms import ProductForm, CategoryForm, BrandForm
from apps.core.models import Product, Category, Brand


# Create your views here.
def welcome(request):
    return render(request, 'core/pages/welcome.html')


@require_http_methods(['GET', 'POST'])
def products(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        description = request.POST.get('description')
        price = request.POST.get('price')
        amount = request.POST.get('amount')
        image = request.FILES.get('image')
        brand = request.POST.get('brand')
        category = request.POST.get('category')


        Product.objects.create(
            name=name,
            description=description,
            price=price,
            amount=amount,
            image=image,
            brand_id=brand,
            category_id=category
        )

        return redirect('core:products')

    products_list = Product.objects.all()
    product_form = ProductForm()

    context = {
        'products': products_list,
        'product_form': product_form
    }

    return render(request, 'core/pages/products.html', context)


def brands(request):
    if request.method == 'POST':
        name = request.POST.get('name')

        Brand.objects.create(
            name=name
        )

        return redirect('core:brands')

    brand_list = Brand.objects.all()
    brand_form = BrandForm()

    context = {
        'brands': brand_list,
        'brand_form': brand_form,
        'user_role': request.user.groups.all()[0].name
    }

    return render(request, 'core/pages/brands.html', context)


def categories(request):
    if request.method == 'POST':
        name = request.POST.get('name')

        Category.objects.create(
            name=name
        )

        return redirect('core:categories')

    category_list = Category.objects.all()
    category_form = CategoryForm()

    context = {
        'categories': category_list,
        'category_form': category_form,
        'user_role': request.user.groups.all()[0].name
    }

    return render(request, 'core/pages/categories.html', context)


class ProductsDetails(DetailView):
    model = Product
    template_name = 'core/pages/product-details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_role'] = self.request.user.groups.all()[0].name
        return context


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'core/pages/product-edit.html'
    success_url = reverse_lazy('core:products')


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('core:products')
    template_name = 'core/pages/product-delete.html'


class BrandDeleteView(DeleteView):
    model = Brand
    success_url = reverse_lazy('core:brands')
    template_name = 'core/pages/brand-delete.html'


class CategoryDeleteView(DeleteView):
    model = Category
    success_url = reverse_lazy('core:categories')
    template_name = 'core/pages/category-delete.html'


def about(request):
    return render(request, 'about_project.html')


def about_core(request):
    return render(request, 'core/about_core.html')

apps/core/templates/core/pages/brand-delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}Edit {{ object.name }}{% endblock  %}

{% block content %}

<div class="container">
    <form action="{% url 'core:category-delete' object.id %}" method="post">
        {% csrf_token %}
        <p>Do you really want to delete <strong>{{ object }}</strong></p>
        <button type="submit" class="btn btn-danger">Confirm</button>
        <a href="{% url 'core:brands' %}" class="btn btn-outline-primary me-2">Back</a>
    </form>
</div>

{% endblock  %}

apps/core/templates/core/pages/brands.html
{% extends "base.html" %}

{% block title %}Products{% endblock %}

{% block content %}

<div class="container">
    <form action="{% url 'core:brands' %}" method="post" class="form-flex">
        {% csrf_token %}
        {% for field in brand_form %}
        <div class="mb-3">
            {{ field_label }}
            {{ field }}
        </div>
        {% endfor %}
        <button type="submit">💾</button>
    </form>
</div>

<div class="container">
    <table class="form-container">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            {% for brand in brands %}
            <tr>
                <td>{{ brand.id }}</td>
                <td>{{ brand.name }}</td>
                {% if user_role == 'admin' %}
                <td>
                    <a href="{% url 'core:brand-delete' brand.id %}" class="btn btn-danger">Delete</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock  %}

apps/core/templates/core/pages/categories.html
{% extends "base.html" %}

{% block title %}Products{% endblock %}

{% block content %}

<div class="container">
    <form action="{% url 'core:categories' %}" method="post" class="form-flex">
        {% csrf_token %}
        {% for field in category_form %}
        <div class="mb-3">
            {{ field }}
        </div>
        {% endfor %}
        <button type="submit">💾</button>
    </form>
</div>

<div class="container">
    <table class="form-container">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
            <tr>
                <td>{{ category.id }}</td>
                <td>{{ category.name }}</td>
                {% if user_role == 'admin' %}
                <td>
                    <a href="{% url 'core:category-delete' category.id %}" class="btn btn-danger">Delete</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock  %}

apps/core/templates/core/pages/category-delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}Edit {{ object.name }}{% endblock  %}

{% block content %}

<div class="container">
    <form action="{% url 'core:category-delete' object.id %}" method="post">
        {% csrf_token %}
        <p>Do you really want to delete <strong>{{ object }}</strong></p>
        <button type="submit" class="btn btn-danger">Confirm</button>
        <a href="{% url 'core:categories' %}" class="btn btn-outline-primary me-2">Back</a>
    </form>
</div>

{% endblock  %}

apps/core/templates/core/pages/product-delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}Edit {{ product.name }}{% endblock  %}

{% block content %}

<div class="container">
    <form action="{% url 'core:product-delete' object.id %}" method="post">
        {% csrf_token %}
        <p>Do you really want to delete <strong>{{ object }}</strong></p>
        <button type="submit" class="btn btn-danger">Confirm</button>
        <a href="{% url 'core:product-details' object.id %}" class="btn btn-outline-primary me-2">Back</a>
    </form>
</div>

{% endblock  %}

apps/core/templates/core/pages/product-details.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ product.name }}{% endblock  %}

{% block content %}

<div class="container">
    <div class="product-root d-flex">
        <div class="prod-image">
            {% if object.image %}
            <img src="{{ object.image.url }}" alt="{{ object.name }}">
            {% endif %}
        </div>
        <div class="prod-main-details" style="margin-left: 20px">
            <div class="prod-name">
                {% if object.brand %}
                <span>{{ object.brand.name }} </span>
                {% endif %}
                <span>{{ object.name }}</span>
                <div class="prod-category">
                    {% if object.category %}
                    <strong>{{ object.category.name }}</strong>
                    {% endif %}
                </div>
            </div>
            <p class="prod-desc">{{ object.description }}</p>
            <div class="prod-price">
                Price: <strong>{{ object.price }}</strong>
            </div>
            <div class="prod-amount">
                Amount: <strong>{{ object.amount }}</strong>
            </div>
        </div>
    </div>
    <div class="prod-controls">
        {% if user_role == 'admin' %}
        <a href="{% url 'core:product-edit' object.id %}" class="btn btn-primary">Edit</a>
        <a href="{% url 'core:product-delete' object.id %}" class="btn btn-danger">Delete</a>
        {% endif %}
    </div>
</div>

{% endblock  %}

apps/core/templates/core/pages/product-edit.html
{% extends "base.html" %}
{% load static %}

{% block title %}Edit {{ product.name }}{% endblock  %}

{% block content %}

<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Change</button>
        <a href="{% url 'core:product-details' object.id %}" class="btn btn-outline-primary me-2">Back</a>
    </form>
</div>

{% endblock  %}

apps/core/templates/core/pages/products.html
{% extends "base.html" %}

{% block title %}Products{% endblock %}

{% block content %}

<div class="container">
    <form action="{% url 'core:products' %}" method="post" class="form-flex">
        {% csrf_token %}
        <input type="text" name="name" placeholder="Name..."><br>
        <textarea name="description" placeholder="Description..."></textarea><br>
        <input type="number" step="0.5" min="0" name="price" placeholder="Price..."><br>
        <input type="number" min="0" name="amount" placeholder="Amount..."><br>
<!--        <input type="file" name="image" placeholder="Image..."><br>-->
        <button type="submit">💾</button>
    </form>
</div>

<div class="container">
    <table class="form-container">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            {% for prod in products %}
            <tr>
                <td><a href="{% url 'core:product-details' prod.id %}">{{ prod.name }}</a></td>
                <td>{{ prod.description }}</td>
                <td>{{ prod.price }}</td>
                <td>{{ prod.amount }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock  %}

apps/core/templates/core/pages/welcome.html
{% extends "base.html" %}
{% load static %}
{% block title %}Welcome{% endblock title %}
{% block header %}{% endblock header %}
{% block content %}
<div class="center-container">
    <a href="{% url 'users:sign-up' %}" class="start-btn">Register</a>
    <a href="{% url 'users:login' %}" class="start-btn">Login</a>
</div>
{% endblock content %}